// enrichment.mjs — colloquial / figurative phrases CLDR keywords lack.
// Appended to each emoji's "label, tags" string before embedding.
// Keys are matched leniently (variation selectors ignored), so ❤ / ❤️ both work.
export const ENRICH = {
  // ── faces: laughter / joy ──
  '😂': 'hilarious, so funny, laughing, lol, dying laughing, cant stop laughing',
  '🤣': 'hilarious, dying, rofl, lmao, funniest thing ever',
  '💀': 'dead, im dead, dying laughing, hilarious, i cant, so funny it killed me',
  '😹': 'hilarious, laughing so hard, funny',
  '😆': 'laughing, hilarious, cracking up, so funny',
  '😄': 'happy, big smile, great mood, joyful',
  '😁': 'grinning, happy, pleased, cheesing',
  '🙂': 'fine, okay i guess, forced smile, everything is fine',
  '🙃': 'sarcastic, everything is fine but not really, being silly, upside down',
  // ── love / affection ──
  '😍': 'in love, obsessed, gorgeous, i want it, so beautiful',
  '🥰': 'in love, adorable, so sweet, feeling loved',
  '😘': 'blowing a kiss, love you, mwah',
  '❤️': 'love, i love you, adore, heart',
  '💔': 'heartbroken, breakup, so sad, hurt, devastated',
  '💕': 'love, affection, crush, sweet',
  '🖤': 'dark, edgy, love, goth',
  '💖': 'sparkling love, adore, so much love',
  '🫶': 'love, so grateful, sending love, appreciate you, heart hands',
  '🥺': 'please, puppy eyes, begging, so cute, pretty please',
  // ── tired / bored / done ──
  '😴': 'boring, putting me to sleep, so tired, nap time, exhausted, snooze',
  '🥱': 'bored, tired, sleepy, unimpressed',
  '😩': 'exhausted, over it, so tired, cant even, struggling',
  '😫': 'exhausted, drained, so tired, done',
  '😮‍💨': 'sigh, relieved, exhausted, finally, deep breath',
  '💤': 'sleeping, tired, asleep, snoring, nap',
  '😑': 'unimpressed, over it, done, no words, whatever',
  '😐': 'awkward, no comment, unimpressed, uncomfortable',
  '🙄': 'annoyed, whatever, over it, sarcastic, ugh, eye roll',
  '😒': 'annoyed, unimpressed, over it, seriously, done',
  // ── stress / awkward / shock ──
  '😬': 'awkward, yikes, cringe, uncomfortable, nervous',
  '😅': 'phew, nervous laugh, awkward, close call, relieved but stressed',
  '😳': 'embarrassed, shocked, flustered, caught off guard',
  '🫠': 'overwhelmed, done, melting, cant deal, dying inside',
  '🤯': 'mind blown, shocked, amazed, cant believe it, exploded',
  '😱': 'shocked, terrified, oh my god, panic, horrified',
  '😰': 'anxious, nervous, cold sweat, stressed, worried',
  '😨': 'scared, anxious, fearful, nervous',
  '🫨': 'shaken, rattled, shocked, overwhelmed',
  // ── thinking / suspicion / smug ──
  '🤔': 'hmm, thinking, suspicious, not sure, let me think',
  '🤨': 'suspicious, skeptical, really, doubtful, sus',
  '😏': 'smug, flirty, knowing, sly, i told you so',
  '😎': 'cool, confident, like a boss, feeling myself, deal with it',
  '👀': 'looking, watching, sus, interesting, side eye, i see that',
  '🧢': 'lying, cap, no cap, fake, not true',
  '🐍': 'sneaky, betrayal, backstabber, sus, snake in the grass',
  '🚩': 'red flag, warning, dealbreaker, bad sign',
  // ── sad / angry / sick ──
  '😭': 'sobbing, crying, so sad, emotional, ugly crying, this hurts',
  '🥹': 'touched, holding back tears, so sweet, emotional, proud',
  '😔': 'sad, disappointed, down, bummed, low',
  '😞': 'let down, disappointed, sad, bummed',
  '😡': 'angry, furious, mad, rage, pissed off',
  '🤬': 'furious, angry, cursing, mad, rage, swearing',
  '😤': 'frustrated, determined, had enough, fed up',
  '🤢': 'gross, disgusting, sick, ew, makes me sick',
  '🤮': 'disgusting, so gross, throwing up, revolting',
  '😷': 'sick, ill, under the weather, protect, flu',
  '🤒': 'sick, fever, ill, unwell, feeling terrible',
  '🥶': 'freezing, so cold, frozen, winter, chilly',
  '🥵': 'so hot, overheating, heat, sweating, summer',
  // ── silly / mischief / respect ──
  '🤡': 'clown, embarrassing myself, foolish, made a fool, joke',
  '😈': 'mischievous, evil plan, up to no good, naughty',
  '😇': 'angel, innocent, halo, sweet, well behaved',
  '🫡': 'respect, yes sir, on it, got it, saluting',
  '🤗': 'hug, comforting, welcome, so sweet, here for you',
  '🥳': 'celebrating, party, so happy, lets go, hooray',
  '🫥': 'invisible, disappearing, checked out, not here',
  // ── gestures ──
  '👍': 'approve, good job, yes, sounds good, agreed, nice',
  '👎': 'no, disapprove, bad, nope, dislike',
  '👏': 'well done, applause, congrats, bravo, praise, good job',
  '🙏': 'please, thank you, grateful, blessed, fingers crossed, hoping',
  '🤞': 'hoping, good luck, fingers crossed, wish me luck',
  '💪': 'strong, gym, workout, powerful, you got this, strength',
  '🤝': 'deal, agreement, teamwork, partnership, agreed',
  '✌️': 'peace, chill, victory, deuces',
  '🤟': 'love you, rock on, ily',
  '👌': 'perfect, okay, nailed it, all good, chefs kiss',
  '🤌': 'chefs kiss, perfect, italian, what do you want',
  '🖐️': 'stop, high five, wait, hand',
  // ── work / tech / money ──
  '💻': 'coding, working, developer, remote work, computer',
  '🧑‍💻': 'coding, developer, programmer, software engineer, when your code finally works',
  '🐛': 'bug, error, glitch, broken code, issue',
  '🚀': 'launch, ship it, growth, blast off, to the moon, fast',
  '📈': 'growth, gains, going up, profit, success, trending up, stonks',
  '📉': 'loss, decline, going down, crash, losing money, downtrend',
  '💰': 'money, cash, rich, profit, wealth, paid',
  '💸': 'spending, expensive, losing money, broke, money flying away',
  '💡': 'idea, lightbulb, good idea, insight, aha moment',
  '🧠': 'smart, big brain, genius, thinking, intelligence',
  '🎯': 'goal, on target, nailed it, bullseye, focused, precise',
  '⚡': 'fast, energy, power, lightning, speed, instant',
  '⏰': 'deadline, wake up, time, running out of time, alarm',
  '🔑': 'key, unlock, important, secret, access',
  '🔒': 'secure, private, locked, safe, encrypted',
  '✅': 'done, completed, yes, correct, approved',
  '❌': 'no, wrong, denied, nope, incorrect, failed',
  // ── celebration / achievement ──
  '🔥': 'amazing, lit, killing it, so good, on fire, hot',
  '💯': 'perfect, one hundred percent, agreed, keeping it real, facts, on point',
  '🎉': 'celebrate, congrats, party, hooray, tada, woohoo',
  '🎊': 'celebrate, party, congrats, festive',
  '🎁': 'present, gift, surprise, birthday',
  '🏆': 'winner, champion, first place, victory, award, won, goated, greatest of all time, the best, legend, elite',
  '🥇': 'first place, winner, gold, champion, number one, goated, greatest, the best, legend',
  '⭐': 'favorite, great, five stars, awesome, top rated',
  '🎓': 'graduation, degree, achievement, graduate, school',
  '🎤': 'singing, karaoke, mic drop, speech, performance',
  // ── food / drink ──
  '☕': 'coffee, need caffeine, morning, tired, latte, wake up',
  '🍕': 'pizza, hungry, food, cheese, slice, italian',
  '🍔': 'burger, hungry, fast food, lunch',
  '🌮': 'taco, tuesday, mexican food, hungry',
  '🍺': 'beer, drinks, happy hour, cheers, pub',
  '🍻': 'cheers, celebrate, drinks, toast, night out',
  '🥂': 'celebrate, cheers, toast, fancy, congratulations',
  '🍷': 'wine, relax, unwind, drinks, fancy',
  '🎂': 'birthday, celebrate, cake, party, dessert',
  '🍰': 'dessert, sweet, cake, treat',
  '🍫': 'chocolate, sweet, treat, craving',
  '🍩': 'donut, sweet, snack, breakfast',
  // ── animals ──
  '🐐': 'greatest of all time, goat, legend, the best, champion',
  '🦄': 'magical, rare, special, one of a kind, startup unicorn',
  '🐶': 'dog, puppy, good boy, pet, loyal',
  '🐱': 'cat, kitten, meow, pet',
  '🦁': 'brave, king, fierce, leader, courage',
  '🐝': 'busy, bee, buzzing, hustle',
  '🦋': 'transformation, beautiful, nervous butterflies, change',
  '🐢': 'slow, taking forever, slow and steady',
  '🐘': 'never forget, huge, memory, big',
  // ── nature / weather ──
  '☀️': 'sunny, hot, summer, bright, nice weather',
  '🌧️': 'rainy, gloomy, wet, storm, sad weather',
  '⛈️': 'storm, chaos, trouble, thunder',
  '🌈': 'hope, pride, colorful, after the storm',
  '❄️': 'cold, snow, winter, freezing, unique',
  '🌊': 'ocean, waves, flood, overwhelmed, surf',
  '🌙': 'night, sleep, goodnight, late',
  // ── misc / objects ──
  '💩': 'crap, terrible, garbage, awful, so bad',
  '🔮': 'future, prediction, fortune, magic, psychic',
  '🪄': 'magic, transformation, effortless, wizard',
  '🧿': 'protection, evil eye, luck',
  '🎮': 'gaming, video games, play, controller',
  '🎧': 'music, listening, focus, headphones',
  '📚': 'studying, reading, learning, school, homework',
  '🧊': 'cold, frozen, ice, chill',
};

// Gen Z / internet slang. The model doesn't natively know these, so each entry
// pairs the SLANG TERM (for literal token overlap with the query) with a
// plain-English meaning (fallback). Merged onto ENRICH at build time.
export const GENZ = {
  '😏': 'rizz, rizzler, rizzling, charisma, smooth talker, charm, flirting game, pulling',
  '😎': 'aura, aura points, aura farming, big aura, cool presence, unbothered, sigma energy',
  '💪': 'mogging, mog, looksmaxxing, dominating, buff, out mogging, gym gains',
  '🗿': 'sigma, sigma male, gigachad, chad, alpha, grindset, stoic, lone wolf, hardcore',
  '🎭': 'larping, larp, pretending, role playing, acting fake, faking it, live action role play',
  '😵‍💫': 'delulu, delusional, in denial, unrealistic, coping, losing it',
  '💯': 'based, facts, no cap, real, agree, keeping it real, valid',
  '💅': 'slay, slayed, ate, ate that up, served, killed it, iconic, understood the assignment',
  '😋': 'bussin, delicious, so good, tasty, fire food, hits different',
  '😐': 'mid, mediocre, average, overrated, not that great, meh',
  '💀': 'cooked, done for, finished, in trouble, so cooked, dead',
  '🤖': 'npc, no personality, robotic, background character, no free will',
  '🌱': 'touch grass, go outside, log off, get some fresh air',
  '🗣️': 'yapping, yap, talking too much, rambling, wont stop talking',
  '🧴': 'glazing, excessive praise, overhyping, sucking up, kissing up',
  '🏆': 'big W, dub, taking the W, win, victory, we won',
  '👎': 'took the L, big L, ratio, loss, fail, taking the L',
  '🤢': 'the ick, ick, turn off, gross, cringe, ew',
  '🥴': 'menty b, mental breakdown, losing it, cant cope, overwhelmed',
  '😤': 'opp, opps, enemy, beef, rival, mad',
  '🤡': 'clown, clown behavior, embarrassing, made a fool, foolish',
  '🍑': 'gyatt, damn, curves',
  '🚽': 'skibidi, brainrot, nonsense, meme',
  '✨': 'its giving, giving, vibes, aesthetic, main character energy, ethereal',
  '🐐': 'goated, goat, greatest of all time, legend, the best',
  // more internet slang → distinctive emoji
  '🎵': 'this slaps, banger, goes hard, absolute banger, on repeat, certified banger',
  '👻': 'ghosted, ghosting, ignored, no reply, left on read, disappeared',
  '🧂': 'salty, bitter, mad, upset, pressed, sour',
  '🤪': 'unhinged, chaotic, wild, crazy, feral, goofy',
  '🤩': 'stan, obsessed fan, super fan, fangirl, hyped, starstruck',
  '💚': 'green flag, good sign, keeper, healthy, wholesome',
  '📸': 'caught in 4k, exposed, receipts, core memory, snapshot',
  '😌': 'vibing, unbothered, at peace, in my zone, hits different, chill',
  '🤫': 'lowkey, keep it quiet, secret, on the down low, hush',
  '📢': 'highkey, loudly, announce, no shame, shout it',
  '🤐': 'say less, zip it, no words, sealed, keep it secret',
  '🧌': 'troll, trolling, goblin mode, menace, internet troll',
  '🥺': 'simp, simping, obsessed, desperate',
  '👍': 'bet, deal, say less, sounds good, okay',
  '👀': 'pov, point of view, caught in 4k, side eye, watching',
  '😱': 'shook, gagged, stunned, no way, speechless',
  '😈': 'goblin mode, menace, chaotic, up to no good',
  '⚡': 'canon event, main character moment, plot twist, meant to be',
};
